import type { Language } from "./language";

// Japanese source strings are stable keys; translating labels never changes rating IDs.
export const englishMessages = {
  "記憶に関する研究 | Mock": "Memory Study | Mock",
  "言語": "Language",
  "表示と生成に使う言語を選択してください。": "Choose the language for the interface and generated content.",
  "質問開始後は言語を変更できません。終了して最初に戻ると変更できます。": "The language is fixed once questions begin. End this session and return to the start to change it.",
  "これはローカル検証用です。質問生成と文章生成で実OpenAI APIを呼び出し、入力内容を外部へ送信します。完了時に結果をローカルCSVへ保存します。": "This is a local test. Questions and stories are generated using the live OpenAI API, which sends your input to an external service. Completed results are saved to a local CSV file.",
  "CSVへ保存中…": "Saving to CSV…",
  "OpenAI APIへ送信中…": "Sending to the OpenAI API…",
  "進行": "Progress",
  "全体の進行": "Overall progress",
  "ステップ": "Step",
  "あなたの断片的な記憶と、質問への回答を材料に、実APIで質問と文章を生成し、その文章について評価します。": "Your memory fragment and answers will be used to generate questions and a story through the live API. You will then rate the story.",
  "質問条件は参加者画面に表示しません": "The assigned question condition is not shown",
  "有効な初期断片を入力した後、質問条件へ割り付けます。": "A question condition is assigned after you submit a valid initial fragment.",
  "説明を読む": "Read the information",
  "参加前の説明": "Before you participate",
  "この検証は、自伝的記憶に関する質問と、AIが作る物語への評価の流れを確認するためのものです。": "This test checks the flow of questions about autobiographical memory and ratings of an AI-generated story.",
  "AIは初期断片と回答を素材に物語を創作します。回答にない情景や感情、出来事が加わることがあります。生成文章は、実際の記憶を復元した記録ではありません。": "AI creates a story using your initial fragment and answers. It may add scenes, emotions, or events you did not report. The generated story is not a reconstruction of your actual memory.",
  "入力した記憶内容と質問への回答は、質問生成と文章生成のためにOpenAI APIへ送信されます。完了時には、初期断片、質問、回答、生成文章、評価結果をこのPCのローカルCSVへ保存します。": "Your memory content and answers are sent to the OpenAI API to generate questions and a story. On completion, your initial fragment, questions, answers, generated story, and ratings are saved to a local CSV file on this computer.",
  "API側のデータ取扱いと、このPCのCSVファイルの管理方法を確認してください。安全に説明できる出来事を選び、答えたくない場合はいつでも中止できます。": "Check how the API handles data and how CSV files on this computer are managed. Choose an event you can safely describe. You may stop at any time if you do not wish to answer.",
  "説明を読み、物語にAIの創作が含まれること、実APIへの送信とローカルCSVへの保存を理解して検証を開始します。": "I have read the information and understand that the story includes AI-created content, my input is sent to the live API, and completed results are saved to a local CSV file.",
  "参加しない": "Do not participate",
  "同意して進む": "Agree and continue",
  "一つの出来事を思い出す": "Recall one event",
  "あなた自身の過去の、習慣や長い期間ではなく、特定の一回の出来事を選んでください。少なくとも1週間前に起きた、安全に説明できる出来事にしてください。楽しかった、普通だった、つらかったなど、感情の種類は問いません。匂いや特定の感覚に意識を向ける必要はありません。": "Choose one specific event from your own past, not a habit or an extended period. It should have happened at least one week ago and be something you can safely describe. It may have been pleasant, ordinary, or difficult. You do not need to focus on smells or any particular sense.",
  "その出来事を一文で書いてください": "Describe the event in one sentence",
  "例：休日に友人と公園を歩いた。": "Example: I walked through a park with a friend on a day off.",
  "氏名、住所、電話番号などは書かないでください。": "Do not include names, addresses, phone numbers, or similar details.",
  "文字": "characters",
  "思い出せない": "I cannot remember",
  "別の出来事も思い出せない": "I cannot remember another event",
  "この内容で進む": "Continue with this event",
  "記憶についての質問": "Questions about your memory",
  "質問": "Question",
  "回答は思い出せる範囲で": "Answer only as far as you remember",
  "質問への回答の進行": "Question progress",
  "APIから質問を取得しています…": "Getting a question from the API…",
  "思い出せる範囲で答えてください": "Answer as far as you remember",
  "分からない、思い出せない、という回答でも構いません。": "It is fine to answer “I don't know” or “I cannot remember.”",
  "ここで中止する": "Stop here",
  "生成中…": "Generating…",
  "回答を終える": "Finish answering",
  "次の質問へ": "Next question",
  "作成された文章": "Generated story",
  "あなたの初期断片と回答を素材に、AIが創作した一人称の物語です。": "This is a first-person story created by AI using your initial fragment and answers.",
  "回答にない描写や出来事が含まれることがあります。実際の記憶を復元した記録ではありません。": "It may contain descriptions or events you did not report. It is not a reconstruction of your actual memory.",
  "文章を評価する": "Rate the story",
  "文章についての評価": "Rate the story",
  "文章を読み、以下の各項目で1〜7のいずれかを選んでください。初期値はありません。": "Read the story and select a rating from 1 to 7 for each item. No option is selected by default.",
  "文章について、各項目に回答してください": "Answer each item about the story",
  "評価を確定して進む": "Confirm ratings and continue",
  "質問についての確認": "Review the questions",
  "質問がどこへ注意を向けたか、文章の品質について回答してください。": "Answer the following items about where the questions directed your attention and the quality of the story.",
  "質問と文章について、各項目に回答してください": "Answer each item about the questions and story",
  "確認を確定して進む": "Confirm and continue",
  "説明": "Debrief",
  "この検証では、質問の向け方が、AIの創作を含む物語の受け取られ方に与える影響を確認します。文章には回答にない描写や出来事が含まれることがあります。": "This test examines how the focus of questions affects responses to stories that include AI-created content. The story may contain descriptions or events you did not report.",
  "質問条件は、出来事の構造、視覚、匂いに関する注意のいずれかでした。条件名は回答終了まで表示していません。": "The questions focused on event structure, visual details, or smells. The condition names were not shown until after you finished answering.",
  "完了すると、初期断片、6つの質問と回答、質問の分岐記録、生成文章と作成記録、条件、言語、評価結果がこのPCの次のファイルへ1行で追記されます。": "On completion, your initial fragment, six questions and answers, question metadata, generated story and annotations, condition, language, and ratings will be appended as one row to this file on this computer:",
  "保存して完了する": "Save and finish",
  "ご協力ありがとうございました": "Thank you for taking part",
  "参加せずに終了しました": "Ended without participating",
  "結果をローカルCSVへ保存しました。": "Your results have been saved to a local CSV file.",
  "保存せずに終了しました。": "The session ended without saving.",
  "入力や条件割付を行わずに終了しました。": "The session ended without submitting input or assigning a condition.",
  "最初に戻る": "Back to the start",
  "研究実施前の検証用 mock ／ 条件・尺度・保存方針は DRAFT です": "Pre-study test mock / Conditions, scales, and storage policy are DRAFT",
  "全くそう感じない": "Not at all",
  "非常に強くそう感じる": "Very strongly",
  "実APIの設定がありません。サーバーの環境変数を確認してください。": "The live API is not configured. Check the server environment variables.",
  "CSVへの保存に失敗しました。サーバーのdataディレクトリを確認してください。": "Could not save the CSV. Check the server's data directory.",
  "生成に失敗しました。入力内容を確認して、もう一度お試しください。": "Generation failed. Check your input and try again.",
  "実APIから検証済み質問を受け取れませんでした。": "The live API did not return a validated question.",
  "生成に失敗しました。もう一度お試しください。": "Generation failed. Please try again.",
  "CSVへの保存に失敗しました。もう一度お試しください。": "Could not save the CSV. Please try again.",
  "実APIから文章を受け取れませんでした。": "The live API did not return a story.",
  "評価対象を見返す": "Review the material being rated",
  "質問を閉じる": "Hide questions",
  "質問を見返す": "Review questions",
  "文章を閉じる": "Hide story",
  "文章を見返す": "Review story",
  "提示された質問": "Presented questions",
  "この文章は、実際にあった個人的出来事を思い返したもののように感じられる。": "This story feels like a recollection of a personal event that actually happened.",
  "この文章は、自分の実体験の語りとして自然に感じられる。": "This story feels natural as an account of my own lived experience.",
  "この文章には、過去の出来事を思い返しているような「思い出らしさ」がある。": "This story has a memory-like quality, as if I were recalling a past event.",
  "この文章を読むと、出来事の場面全体を一つのまとまりとして思い描ける。": "Reading this story, I can picture the whole scene of the event as a coherent whole.",
  "場所の広がりや、人物・物の配置がはっきり思い浮かぶ。": "I can clearly picture the layout of the place and the positions of people and objects.",
  "自分がその場にいるように、場面を内側から見渡せる感じがする。": "I feel as though I can look around the scene from within, as if I were there.",
  "この文章は、全体として鮮明で具体的に感じられる。": "Overall, this story feels vivid and concrete.",
  "この文章には、場面や出来事を生き生きと感じさせる細部が含まれている。": "This story contains details that make the scene or event feel alive.",
  "出来事の様子が、ぼんやりではなく、はっきり伝わってくる。": "The event comes across clearly rather than vaguely.",
  "この文章を読むと、その出来事のときに感じた感情がよみがえる。": "Reading this story brings back the emotions I felt during the event.",
  "この文章を読んでいる間、当時の感情をもう一度体験しているように感じる。": "While reading this story, I feel as though I am experiencing those emotions again.",
  "この文章は、当時の感情を自分の中に呼び戻す。": "This story reawakens the emotions I felt at the time.",
  "提示された質問は、出来事の中での行動、人物、やり取り、起きた順序に、どの程度あなたの注意を向けましたか。": "To what extent did the questions direct your attention to actions, people, interactions, and the order of events?",
  "提示された質問は、物や人の見た目、色、明るさ、配置などの視覚的な詳細に、どの程度あなたの注意を向けましたか。": "To what extent did the questions direct your attention to visual details, such as the appearance of objects or people, colors, brightness, and arrangement?",
  "提示された質問は、匂いや空気のにおいに、どの程度あなたの注意を向けましたか。": "To what extent did the questions direct your attention to smells or scents in the air?",
  "実際には思い出せない詳細まで答えるよう求められていると、どの程度感じましたか。": "To what extent did you feel asked to provide details you could not actually remember?",
  "あなたの回答は、推測ではなく、実際に思い出せた内容にどの程度基づいていましたか。": "To what extent were your answers based on what you actually remembered rather than guesses?",
  "作成された文章には、あなたが答えていない内容が、どの程度含まれていたと感じましたか。": "To what extent did you feel the generated story included content you had not provided?",
  "全く向けなかった": "Not at all",
  "非常に強く向けた": "Very strongly",
  "全く感じなかった": "Not at all",
  "非常に強く感じた": "Very strongly",
  "全く基づいていなかった": "Not at all",
  "完全に基づいていた": "Entirely",
  "全く含まれていなかった": "None at all",
  "非常に多く含まれていた": "A great deal"
} as const;

export type MessageKey = keyof typeof englishMessages;

export function translate(language: Language, key: MessageKey): string {
  return language === "en" ? englishMessages[key] : key;
}

